### ISSUE TITLE
Issues in download

### ISSUE THREAD

**Issue by cpkgroup** [SolidHal/spotify-ripper#13]
Hi, I have premium Spotify account and use this command but doesn't work:

vagrant@vagrant-ubuntu-trusty-64:~$ spotify-ripper -u myusername -p mypassword spotify:track:2bOcIC4wFd6OENI7UGHzIg
Spotify Ripper - v2.9.1
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	160 kbps
  Unicode support:	Yes
  Output directory:	/vagrant/Music
  Settings directory:	/home/vagrant/.spotify-ripper
  Format String:	{artist} - {album}/{idx:3} - {artist} - {track_name}.{ext}
  Overwrite files:	No

Please copy your spotify_appkey.key to /home/vagrant/.spotify-ripper, or use the --key|-k option

Can't I download without appkey? or Do I have any other problems?
How can I generate appkey if it's necessary?

Thanks.

**Comment by NickBrisebois** [comment]
Yeah i'm wondering this too. I see that spotify no longer issues app keys so is this script even usable anymore? I can't see anything that says its not but I would understand if it isn't. I'd just like confirmation

**Comment by SolidHal** [comment]
Since this only uses the webapi for song removal and retreiving the playlist contents but uses the old api for everything else unfortunately both the appkey and the web api key are required. At some point I plan to rewrite this to use the webapi entirely, however it won't be high on the todo list while the old api still has some functionality.

**Comment by bradc87** [comment]
I would like to use this script, but cannot get an appkey from spotify
